/* Role-based theme tokens for ScenarioPlayer and any component that needs them.
   Extracted from ScenarioPlayer so it can be imported without pulling the whole page. */

export const ROLE_THEMES = {
    fertilizerengineer: {
        bg: 'from-amber-950 via-slate-950 to-orange-950',
        accent: 'from-amber-500 to-orange-500',
        border: 'border-amber-500/30',
        text: 'text-amber-400',
        glow: 'shadow-amber-500/20',
        location: '📍 ADNOC Distribution — Abu Dhabi, UAE',
        alert: '⛽ Holiday Weekend — High Demand Alert',
        alertColor: 'bg-amber-500/10 border-amber-500/30 text-amber-300',
        hudColor: '#f59e0b',
    },
    environmentalscientist: {
        bg: 'from-emerald-950 via-slate-950 to-teal-950',
        accent: 'from-emerald-500 to-teal-500',
        border: 'border-emerald-500/30',
        text: 'text-emerald-400',
        glow: 'shadow-emerald-500/20',
        location: '📍 Environmental Monitoring Station — UAE',
        alert: '🌿 Ecosystem Alert — Urgent Assessment',
        alertColor: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300',
        hudColor: '#10b981',
    },
    biomedicalresearcher: {
        bg: 'from-purple-950 via-slate-950 to-pink-950',
        accent: 'from-purple-500 to-pink-500',
        border: 'border-purple-500/30',
        text: 'text-purple-400',
        glow: 'shadow-purple-500/20',
        location: '📍 Biomedical Research Lab — UAE University',
        alert: '🧬 Research Priority — Critical Case',
        alertColor: 'bg-purple-500/10 border-purple-500/30 text-purple-300',
        hudColor: '#a855f7',
    },
    spacemissionchemist: {
        bg: 'from-blue-950 via-slate-950 to-indigo-950',
        accent: 'from-blue-500 to-indigo-500',
        border: 'border-blue-500/30',
        text: 'text-blue-400',
        glow: 'shadow-blue-500/20',
        location: '📍 Space Mission Control — Deep Space',
        alert: '🚀 Mission Critical — Crew Safety Alert',
        alertColor: 'bg-blue-500/10 border-blue-500/30 text-blue-300',
        hudColor: '#3b82f6',
    },
    industrialchemist: {
        bg: 'from-red-950 via-slate-950 to-rose-950',
        accent: 'from-red-500 to-rose-500',
        border: 'border-red-500/30',
        text: 'text-red-400',
        glow: 'shadow-red-500/20',
        location: '📍 Chemical Manufacturing Plant — UAE',
        alert: '⚠️ Safety Alert — Immediate Action Required',
        alertColor: 'bg-red-500/10 border-red-500/30 text-red-300',
        hudColor: '#ef4444',
    },
    geologist: {
        bg: 'from-orange-950 via-slate-950 to-amber-950',
        accent: 'from-orange-500 to-amber-500',
        border: 'border-orange-500/30',
        text: 'text-orange-400',
        glow: 'shadow-orange-500/20',
        location: '📍 Geological Survey Site — UAE',
        alert: '🪨 Hazard Alert — Site Assessment Active',
        alertColor: 'bg-orange-500/10 border-orange-500/30 text-orange-300',
        hudColor: '#f97316',
    },
    pharmaceuticalscientist: {
        bg: 'from-teal-950 via-slate-950 to-cyan-950',
        accent: 'from-teal-500 to-cyan-500',
        border: 'border-teal-500/30',
        text: 'text-teal-400',
        glow: 'shadow-teal-500/20',
        location: '📍 Pharmaceutical Lab — UAE',
        alert: '💊 Production Alert — Quality Control',
        alertColor: 'bg-teal-500/10 border-teal-500/30 text-teal-300',
        hudColor: '#14b8a6',
    },
    energyengineer: {
        bg: 'from-yellow-950 via-slate-950 to-amber-950',
        accent: 'from-yellow-500 to-amber-500',
        border: 'border-yellow-500/30',
        text: 'text-yellow-400',
        glow: 'shadow-yellow-500/20',
        location: '📍 Energy Grid Control — UAE',
        alert: '⚡ Grid Alert — High Demand Active',
        alertColor: 'bg-yellow-500/10 border-yellow-500/30 text-yellow-300',
        hudColor: '#eab308',
    },
    processsafetyengineer: {
        bg: 'from-cyan-950 via-slate-950 to-blue-950',
        accent: 'from-cyan-500 to-blue-500',
        border: 'border-cyan-500/30',
        text: 'text-cyan-400',
        glow: 'shadow-cyan-500/20',
        location: '📍 ADNOC Gas Operations — Abu Dhabi, UAE',
        alert: '🧯 Pressure Alert — Engineering Review Required',
        alertColor: 'bg-cyan-500/10 border-cyan-500/30 text-cyan-300',
        hudColor: '#06b6d4',
    },
};

export const DEFAULT_THEME = {
    bg: 'from-slate-900 via-slate-950 to-slate-900',
    accent: 'from-teal-500 to-emerald-500',
    border: 'border-teal-500/30',
    text: 'text-teal-400',
    glow: 'shadow-teal-500/20',
    location: '📍 Science Lab',
    alert: null,
    alertColor: '',
    hudColor: '#06b6d4',
};
