/* Role-based theme tokens for ScenarioPlayer and any component that needs them.
   Extracted from ScenarioPlayer so it can be imported without pulling the whole page. */

export const ROLE_THEMES = {
    fertilizerengineer: {
        bg: 'from-amber-50/70 via-slate-50 to-orange-100/50',
        accent: 'from-amber-600 to-orange-600',
        border: 'border-amber-200',
        text: 'text-amber-900',
        glow: 'shadow-amber-500/10',
        location: '📍 ADNOC Distribution — Abu Dhabi, UAE',
        alert: '⛽ Holiday Weekend — High Demand Alert',
        alertColor: 'bg-amber-100/80 border-amber-200/60 text-amber-950',
        hudColor: '#d97706',
    },
    environmentalscientist: {
        bg: 'from-emerald-50/70 via-slate-50 to-teal-100/50',
        accent: 'from-emerald-600 to-teal-600',
        border: 'border-emerald-200',
        text: 'text-emerald-900',
        glow: 'shadow-emerald-500/10',
        location: '📍 Environmental Monitoring Station — UAE',
        alert: '🌿 Ecosystem Alert — Urgent Assessment',
        alertColor: 'bg-emerald-100/80 border-emerald-200/60 text-emerald-950',
        hudColor: '#059669',
    },
    biomedicalresearcher: {
        bg: 'from-purple-50/70 via-slate-50 to-pink-100/50',
        accent: 'from-purple-600 to-pink-600',
        border: 'border-purple-200',
        text: 'text-purple-900',
        glow: 'shadow-purple-500/10',
        location: '📍 Biomedical Research Lab — UAE University',
        alert: '🧬 Research Priority — Critical Case',
        alertColor: 'bg-purple-100/80 border-purple-200/60 text-purple-950',
        hudColor: '#9333ea',
    },
    spacemissionchemist: {
        bg: 'from-blue-50/70 via-slate-50 to-indigo-100/50',
        accent: 'from-blue-600 to-indigo-600',
        border: 'border-blue-200',
        text: 'text-blue-900',
        glow: 'shadow-blue-500/10',
        location: '📍 Space Mission Control — Deep Space',
        alert: '🚀 Mission Critical — Crew Safety Alert',
        alertColor: 'bg-blue-100/80 border-blue-200/60 text-blue-950',
        hudColor: '#2563eb',
    },
    industrialchemist: {
        bg: 'from-red-50/70 via-slate-50 to-rose-100/50',
        accent: 'from-red-600 to-rose-600',
        border: 'border-red-200',
        text: 'text-red-900',
        glow: 'shadow-red-500/10',
        location: '📍 Chemical Manufacturing Plant — UAE',
        alert: '⚠️ Safety Alert — Immediate Action Required',
        alertColor: 'bg-red-100/80 border-red-200/60 text-red-950',
        hudColor: '#dc2626',
    },
    geologist: {
        bg: 'from-orange-50/70 via-slate-50 to-amber-100/50',
        accent: 'from-orange-600 to-amber-600',
        border: 'border-orange-200',
        text: 'text-orange-900',
        glow: 'shadow-orange-500/10',
        location: '📍 Geological Survey Site — UAE',
        alert: '🪨 Hazard Alert — Site Assessment Active',
        alertColor: 'bg-orange-100/80 border-orange-200/60 text-orange-950',
        hudColor: '#ea580c',
    },
    pharmaceuticalscientist: {
        bg: 'from-teal-50/70 via-slate-50 to-cyan-100/50',
        accent: 'from-teal-600 to-cyan-600',
        border: 'border-teal-200',
        text: 'text-teal-900',
        glow: 'shadow-teal-500/10',
        location: '📍 Pharmaceutical Lab — UAE',
        alert: '💊 Production Alert — Quality Control',
        alertColor: 'bg-teal-100/80 border-teal-200/60 text-teal-950',
        hudColor: '#0d9488',
    },
    energyengineer: {
        bg: 'from-yellow-50/70 via-slate-50 to-amber-100/50',
        accent: 'from-yellow-600 to-amber-600',
        border: 'border-yellow-200',
        text: 'text-yellow-900',
        glow: 'shadow-yellow-500/10',
        location: '📍 Energy Grid Control — UAE',
        alert: '⚡ Grid Alert — High Demand Active',
        alertColor: 'bg-yellow-100/80 border-yellow-200/60 text-yellow-950',
        hudColor: '#ca8a04',
    },
    processsafetyengineer: {
        bg: 'from-cyan-50/70 via-slate-50 to-blue-100/50',
        accent: 'from-cyan-600 to-blue-600',
        border: 'border-cyan-200',
        text: 'text-cyan-900',
        glow: 'shadow-cyan-500/10',
        location: '📍 ADNOC Gas Operations — Abu Dhabi, UAE',
        alert: '🧯 Pressure Alert — Engineering Review Required',
        alertColor: 'bg-cyan-100/80 border-cyan-200/60 text-cyan-950',
        hudColor: '#0891b2',
    },
};

export const DEFAULT_THEME = {
    bg: 'from-slate-50 via-slate-50 to-slate-100/50',
    accent: 'from-teal-600 to-emerald-600',
    border: 'border-teal-200',
    text: 'text-teal-900',
    glow: 'shadow-teal-500/10',
    location: '📍 Science Lab',
    alert: null,
    alertColor: '',
    hudColor: '#0d9488',
};
